// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhtbyabxblwbivnccppg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodGJ5YWJ4Ymx3Yml2bmNjcHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjYxMjksImV4cCI6MjA3NDUwMjEyOX0.jDgmBRASY67e-WQhhhjnoa5NyJtn6lI1AFsL2LIrqls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});